import Head from 'next/head'
import Image from 'next/image'
import Feed from '../components/Feed'
import Sidebar from '../components/Sidebar'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=' min-h-screen max-w-[100%] mx-auto '>
        <Sidebar />
        
        <Feed />
        {/* Widgets */}
        {/* Modal */}
      </main>

      
    </div>
  )
}
